CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,salt TEXT NOT NULL,password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id));
CREATE TABLE IF NOT EXISTS tickets(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',assignee BIGINT REFERENCES users(id),external_id TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS comments(id BIGSERIAL PRIMARY KEY,ticket_id BIGINT NOT NULL REFERENCES tickets(id),body TEXT NOT NULL);
